name: Deployment
on:
  workflow_dispatch:
    
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: https://github.com
    steps:
      - name: deploy
        run: echo ${{ secrets.sec }}
      - name: global
        run: echo ${{ secrets.G_TOKEN }}
        
