name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: https://github.com
    steps:
      - name: deploy
        run: echo ${{ secrets.sec }}
        
