name: Create issue on commit

on: [ push ]

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        id: P
        run: echo 2+3
      - name: if failure
        run: echo ${{ steps.P.outputs }}
        if: failure()