name: matrix strategy
on:
  workflow_dispatch:
    
jobs:
  matrix-simple:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node_version: [6, 10]
        include:
          - node_version: 4
            os: ubuntu-latest
            is_ubuntu_16: "true"
        exclude:
          - node_version: 6
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_16: ${{ matrix.is_ubuntu_16 }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: env check 
        run: echo $IS_UBUNTU_16     