name: matrix strategy
on: push
jobs:
  matrix-simple:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [6, 8, 10]
        exclude:
          - os: macos-latest
            node-version: 8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: node version 
        run: node -v    