name: Create issue on commit

on: [ push ]

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        continue-on-error: true
        id: P
        run: echho 2+3
      - name: if failure
        run: echo "Run Successfully"
        if: ${{ failure() }}