name: shell commands workflow

on: 
  schedule:
    - cron: "* * * * *"
  push:
  
jobs:
  run-on-shell-job:
    runs-on: ubuntu-latest
    steps:
      - name: shell commands
        run: echo "Hell-O world"
      - name: multiline commands
        run: |
          node -v
          npm -v
