name: matrix strategy
on: push
jobs:
  matrix-simple:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        run: ['run1', 'run2']
    steps:
      - name: matrix run
        run: echo Run ${{ matrix.run }}