name: shell commands workflow

on: 
  push:
    branches:
      - "main"
      - "feature/*"
      - "feature/**"
      - "!feature/"
  
jobs:
  run-on-shell-job:
    runs-on: ubuntu-latest
    steps:
      - name: shell commands
        run: echo "Hell-O world"
      - name: multiline commands
        run: |
          node -v
          npm -v
