name: shell commands workflow

on: 
  - push

jobs:
  run-on-shell-job:
    runs-on: ubuntu-latest
    steps:
      - name: shell commands
        run: echho "Hell-O world"
      - name: multiline commands
        run: |
          node -v
          npm -v