name: shell commands workflow

on: 
  - push

jobs:
  run-on-shell-job:
    runs-on: ubuntu-latest
    steps:
      - name: shell commands
        run: echo "Hell-O world"
      - name: multiline commands
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  runs-on-windows:
    runs-on: windows-latest
    steps:
      - name: get location
        run: Get-Location
      - name: get bash pwd
        run: pwd
        shell: bash