name: Create issue on commit

on: [ push ]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps: 
      - name: Use Git Token
        run: |
          echo ${{ secrets.GITHUB_TOKEN}}
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch
          git branch --set-upstream-to=origin/main
          git pull
          ls -a